{
 "title": "FruitsBasket API Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\r\n    rate(http_requests_received_total[5m]),\r\n    \"endpoint\",\r\n    \"$1\",\r\n    \"endpoint\",\r\n    \"api/v\\\\{version:apiVersion\\\\}/(.*)\"\r\n)",
     "legendFormat": "{{method}} {{endpoint}} - {{code}}"
    }
   ]
  },
  {
   "title": "API Request Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method, endpoint) (\r\n  label_replace(\r\n    rate(http_request_duration_seconds_bucket[5m]),\r\n    \"endpoint\",\r\n    \"$1\",\r\n    \"endpoint\",\r\n    \"api/v\\\\{version:apiVersion\\\\}/(.*)\"\r\n  )\r\n))",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Active Fruits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fruitsbasket_active_fruits_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fruit Operations",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\r\n    http_request_duration_seconds_count,\r\n    \"endpoint\",\r\n    \"$1\",\r\n    \"endpoint\",\r\n    \"api/v\\\\{version:apiVersion\\\\}/(.*)\"\r\n)",
     "legendFormat": "{{method}} {{endpoint}} - {{code}}"
    }
   ]
  }
 ]
}